sudo: required
language: c
os:
  - linux
services:
  - docker
env:
  - PG_VERSION=9.6.5
  - PG_VERSION=10.0

before_install:
  - docker run -d --name pgbuild -v ${TRAVIS_BUILD_DIR}:/build postgres:${PG_VERSION}-alpine
install:
  - docker exec -it pgbuild /bin/sh -c "apk add --no-cache --virtual .build-deps coreutils dpkg-dev gcc libc-dev make util-linux-dev diffutils cmake && mkdir -p /build/debug && cd /build/debug && cmake .. -DCMAKE_BUILD_TYPE=Debug && make install && chown -R postgres:postgres /build/"
script:
  - docker exec -u postgres -it pgbuild /bin/sh -c "make -C /build/debug installcheck PG_REGRESS_OPTS='--temp-instance=/tmp/pgdata'"
after_failure:
  - docker exec -it pgbuild cat /build/debug/test/regression.diffs
after_script:
  - docker rm -f pgbuild

jobs:
  include:
    - stage: test
      script:
        - PGTEST_TMPDIR=/tmp/ bash -x ./scripts/test_updates.sh
