# Check our codebase for defective programming patterns
name: Coccinelle
"on":
  pull_request:
  push:
    branches:
      - main
      - prerelease_test
permissions:
  contents: read

jobs:
  coccinelle:
    name: Coccinelle
    # coccinelle version in ubuntu-latest (20.04) is too old so we run
    # this in jammy (22.04)
    runs-on: ubuntu-22.04

    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install coccinelle

    - name: Checkout TimescaleDB
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - name: Run coccinelle
      run: |
        ./scripts/coccinelle.sh

    - name: Save coccinelle.diff
      if: always()
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: coccinelle.diff
        path: coccinelle.diff

