name: Coverity Results
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  defects:
    name: Show Coverity Defect Report
    runs-on: ubuntu-latest
    steps:
      - name: Get Coverity tools
        run: |
          wget https://scan.coverity.com/download/linux64 --post-data "token=${{ secrets.COVERITY_TOKEN }}&project=timescale%2Ftimescaledb" -O coverity_tool.tgz -q
          tar xf coverity_tool.tgz
          mv cov-analysis-linux64-* coverity
      - name: Show Info
        run: |
          ls -lR
      - name: Get Defects Report
        run: |
          $COVBIN/cov-manage-im --mode defects --show --project=timescale-timescaledb
