name: Additional tests
on:
  schedule:
    # run daily 20:00 on main branch
    - cron: '0 20 * * *'
  push:
    branches:
      - prerelease_test
jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      pg_latest: ${{ steps.setter.outputs.PG_LATEST }}
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Read configuration
      id: setter
      run: python .github/gh_config_reader.py

  backup_and_restore:
    name: Backup and restore
    runs-on: ubuntu-latest
    needs: config
    strategy:
      fail-fast: false
      matrix:
        pg: ${{ fromJson(needs.config.outputs.pg_latest) }}
    env:
      PG_VERSION: ${{ matrix.pg }}

    steps:
    - name: Checkout TimescaleDB
      uses: actions/checkout@v2

    - name: Test recovery using restore points
      run: |
        ./scripts/docker-run-restore-points-test.sh
