name: Additional tests
on:
  schedule:
    # run daily 20:00 on master branch
    - cron: '0 20 * * *'
  push:
    branches:
      - prerelease_test
jobs:
  backup_and_restore:
    name: Backup and restore
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pg: [12, 13, 14]
    env:
      PG_MAJOR: ${{ matrix.pg }}
      PG_VERSION: ${{ matrix.pg }}

    steps:
    - name: Checkout TimescaleDB
      uses: actions/checkout@v2

    - name: Test recovery using restore points
      run: |
        ./scripts/docker-run-restore-points-test.sh
