name: Docker
on: ['pull_request']
jobs:
  docker:
    name: Test-build PG${{ matrix.pg_version }} Docker image for ${{ matrix.flavor }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pg_version: [12, 13]
        flavor: ['bitnami', 'alpine']
    steps:
      - name: Checkout TimescaleDB
        uses: actions/checkout@v2
      - name: Read version info
        id: info
        shell: perl -n {0} version.config
        run: |
          if (/^update_from_version\s*=\s*(\S+)/) {
            print "::set-output name=from_version::$1\n";
            print "from_version: $1\n";
          }
          if (/^version\s*=\s*(\S+)/) {
            print "::set-output name=version::$1\n";
            print "version: $1\n";
          }
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        uses: docker/build-push-action@v2
        id: build
        with:
          load: true
          file: ./Dockerfile.${{ matrix.flavor }}
          tags: timescale/timescaledb:${{ steps.info.outputs.version }}-pg${{ matrix.pg_version }}
          build-args: |
            PG_VERSION=${{ matrix.pg_version }}
            TS_VERSION=${{ steps.info.outputs.version }}
            PREV_TS_VERSION=${{ steps.info.outputs.from_version }}
      - name: Inspect image
        run: |
          docker images

