# Ignoring version of the corresponding workflow. These files are
# needed to run required workflows even when the real workflow is not
# executed because some files were ignored.
name: Regression
on:
  push:
    branches:
      - prerelease_test
    paths:
      - '**.md'
      - 'LICENSE*'
      - NOTICE
  pull_request:
    paths:
      - '**.md'
      - 'LICENSE*'
      - NOTICE
jobs:
  matrixbuilder:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Build matrix
      id: set-matrix
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]] ;
        then
          git fetch origin ${{ github.base_ref }}:base
          .github/gh_matrix_builder.py ${{ github.event_name }} base
        else
          .github/gh_matrix_builder.py ${{ github.event_name }}
        fi

  regress:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "No build required"
