name: Test Update and Downgrade
on:
  schedule:
    # run daily 20:00 on main branch
    - cron: '0 20 * * *'
  push:
    branches:
      - prerelease_test
  pull_request:
jobs:
  update_test:
    name: Update test PG${{ matrix.pg }}
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        pg: ["12.11", "13.7", "14.3"]
      fail-fast: false
    env:
      PG_VERSION: ${{ matrix.pg }}
      POSTGRES_HOST_AUTH_METHOD: trust
    steps:
    - name: Checkout TimescaleDB
      uses: actions/checkout@v2

    - name: Update tests ${{ matrix.pg }}
      run: |
        PG_MAJOR=$(echo "${{ matrix.pg }}" | sed -e 's![.].*!!')
        ./scripts/test_updates_pg${PG_MAJOR}.sh

    - name: Update diff
      if: failure()
      run: |
        find . -name "update_test.*.diff.*" -maxdepth 1 | xargs -IFILE sh -c "echo '\nFILE\n';cat FILE"

    - name: Upload Artifacts
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: Extension update diff ${{ matrix.pg }}
        path: update_test.*.diff.*

  downgrade_test:
    name: Downgrade test PG${{ matrix.pg }}
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        pg: ["12.11", "13.7", "14.3"]
      fail-fast: false
    env:
      PG_VERSION: ${{ matrix.pg }}
      POSTGRES_HOST_AUTH_METHOD: trust
      GENERATE_DOWNGRADE_SCRIPT: ON
    steps:
    - name: Checkout TimescaleDB
      uses: actions/checkout@v2

    # We need the tags to be able to build a downgrade script.
    - name: Fetch all tags
      run: git fetch --tags && git tag

    - name: Downgrade tests ${{ matrix.pg }}
      env:
        TEST_VERSION: v7
      run: |
        DOWNGRADE_TO=$(grep '^downgrade_to_version = ' version.config | sed -e 's!^[^=]\+ = !!')
        PG_MAJOR=$(echo "${{ matrix.pg }}" | sed -e 's![.].*!!')
        UPDATE_FROM_TAG=${DOWNGRADE_TO}-pg${PG_MAJOR}
        export UPDATE_FROM_TAG
        scripts/test_downgrade_from_tag.sh

    - name: Downgrade diff
      if: failure()
      run: |
        find . -name "downgrade_test.*.diff.*" -maxdepth 1 | xargs -IFILE sh -c "echo '\nFILE\n';cat FILE"

    - name: Upload Artifacts
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: Extension downgrade diff ${{ matrix.pg }}
        path: downgrade_test.*.diff.*
